#!/bin/sh

die() {
  echo "$1"
  exit 1
}

first="$1"
second="$2"

set -euf pipefail

DEVELOP="develop"
CANDIDATE="candidate"
MAIN="main"

help() {
  cat <<HELPTEXT

Usage: flow (feature_start|feature_finish
            |release_start|release_finish
            |hotfix_start|hotfix_finish) [branchname]

This script attempts to follow the cactus model / threeflow
https://www.nomachetejuggling.com/2017/04/09/a-different-branching-strategy/

(init):
    Creates the original 3 branches: develop, candidate and main

(fs|feature_start) [branchname]:
    This will create the specified feature branch off of develop

(ff|feature_finish) [branchname]:
    This will merge the specified feature branch back into develop

(rs|release_start):
    This will start a new release by merging the develop branch into candidate.
    It will tag the place where it diverges from develop.

(rf|release_finish):
    This will tag the release, and merge the candidate branch into BOTH develop and main.
    The merge to develop will be a --no-ff, and the merge to main will be a fastforward.

(hs|hotfix_start) [branchname]:
    This will start a hotfix branch off of the main branch.
    It will tag the place where it diverges from main.
    Since hotfix branches are temporary, they do not have a static name.

(hf|hotfix_finish) [branchname]:
    This will tag the hotfix, and merge it into main, candidate, and develop.

(view)
    Shows the current state of git, within the terminal.

-------------------------------------------------------------------------------

HELPTEXT
}

##########
## Util
##########

get_date() {
  date "+%y%m%d_%H%M%S"
}

automerge() {
  git checkout "$1"
  git pull
  git merge --no-ff --no-edit "$2"
  git push origin "$1"
}

automerge_integration() {
  integration_branch="$2_to_$1_$(get_date)"
  git checkout "$1"
  git pull
  git co -b $integration_branch
  git merge --no-edit "$2"
  git push origin "$integration_branch"
}

merge() {
  git checkout "$1"
  git pull
  git merge --no-ff "$2"
  git push origin "$1"
}

fastForwardMerge() {
  git checkout "$1"
  git pull
  git merge --ff "$2"
  git push origin "$1"
}

tag() {
  git tag "$1"
  git push origin "$1"
}

squashMerge() {
  if output=$(git status --porcelain) && [ -z "$output" ]; then
    git checkout "$1"
    git pull
    git merge --squash "$2" && git commit
    git push origin "$1"
  else
    die "No action taken. There are uncommitted changes in the working directory."
  fi
}

initBranches() {
  git checkout -b $DEVELOP
  git checkout -b $CANDIDATE
  git checkout -b $MAIN
}

##########
## Feature
##########

featureCut() {
  git checkout $DEVELOP
  git checkout -b "$1"
}

featureClose() {
  squashMerge $DEVELOP "$1"
}

##########
## Patch
##########

patchCut() {
  git checkout $CANDIDATE
  git checkout -b "$1"
}

patchClose() {
  squashMerge $CANDIDATE "$1"
}

##########
## Release
##########

releaseCut() {
  automerge $CANDIDATE $DEVELOP
  tag release_start_"$(get_date)"
}

releaseClose() {
  changelog="$(git log --oneline candidate...main | cat)"

  fastForwardMerge $MAIN $CANDIDATE
  tag release_"$(get_date)"

  echo
  echo "================================"
  echo " Changelog"
  echo "================================"
  echo
  echo "$changelog"
  echo
  echo "================================"
  echo

  automerge_integration $DEVELOP $CANDIDATE

}

##########
## Hotfix
##########

hotfixCut() {
  git checkout $MAIN
  git checkout -b "$1"
  tag hotfix_start_"$(get_date)"
}

hotfixClose() {
  automerge $MAIN "$1"
  tag hotfix_"$(get_date)"
  read -s -n 1 -p "Merge to main complete. Press any key to attempt a merge to candidate, and develop."

  automerge $CANDIDATE $MAIN
  automerge $DEVELOP $MAIN
}

main() {
  if [ -z "$1" ]; then
    help
    exit 1
  fi
  case "$1" in
  "help")
    help
    ;;
  "init")
    initBranches
    ;;
  "feature_start" | "fs")
    if [ -z "$2" ]; then
      help
      die "Requires a branch name."
    fi
    featureCut "$2"
    ;;
  "feature_finish" | "ff")
    if [ -z "$2" ]; then
      help
      die "Requires a branch name."
    fi
    featureClose "$2"
    ;;
  "patch_start" | "ps")
    if [ -z "$2" ]; then
      help
      die "Requires a branch name."
    fi
    patchCut "$2"
    ;;
  "patch_finish" | "pf")
    if [ -z "$2" ]; then
      help
      die "Requires a branch name."
    fi
    patchClose "$2"
    ;;
  "release_start" | "rs")
    releaseCut
    ;;
  "release_finish" | "rf")
    releaseClose
    ;;
  "hotfix_start" | "hs")
    if [ -z "$2" ]; then
      help
      die "Requires a branch name."
    fi
    hotfixCut "$2"
    ;;
  "hotfix_finish" | "hf")
    if [ -z "$2" ]; then
      help
      die "Requires a branch name."
    fi
    hotfixClose "$2"
    ;;
  "view")
    git log \
      --graph \
      --abbrev-commit \
      --decorate \
      --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' \
      --all
    ;;
  *)
    die "\"$1\" not recognized"
    ;;
  esac
}

main "$first" "$second"
